services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    restart: unless-stopped
  
  db:
    container_name: db
    image: postgres:17
    ports:
      - 5433:5432
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: