FROM python:3.13

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./entrypoint.dev.sh .
RUN chmod +x /app/entrypoint.dev.sh

CMD ["/app/entrypoint.dev.sh"]
